car-listings/config/routes.rb
Rails.application.routes.draw do
  resources :saleswomen
  resources :prospects
  resources :car_infos
  resources :salesmen
  resources :dealerships
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

car-listings/app/models/car_info.rb
class CarInfo < ApplicationRecord
end

car-listings/app/controllers/car_infos_controller.rb
class CarInfosController < ApplicationController
  before_action :set_car_info, only: [:show, :edit, :update, :destroy]

  # GET /car_infos
  # GET /car_infos.json
  def index
    @car_infos = CarInfo.all
  end

  # GET /car_infos/1
  # GET /car_infos/1.json
  def show
  end

  # GET /car_infos/new
  def new
    @car_info = CarInfo.new
  end

  # GET /car_infos/1/edit
  def edit
  end

  # POST /car_infos
  # POST /car_infos.json
  def create
    @car_info = CarInfo.new(car_info_params)

    respond_to do |format|
      if @car_info.save
        format.html { redirect_to @car_info, notice: 'Car info was successfully created.' }
        format.json { render :show, status: :created, location: @car_info }
      else
        format.html { render :new }
        format.json { render json: @car_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /car_infos/1
  # PATCH/PUT /car_infos/1.json
  def update
    respond_to do |format|
      if @car_info.update(car_info_params)
        format.html { redirect_to @car_info, notice: 'Car info was successfully updated.' }
        format.json { render :show, status: :ok, location: @car_info }
      else
        format.html { render :edit }
        format.json { render json: @car_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /car_infos/1
  # DELETE /car_infos/1.json
  def destroy
    @car_info.destroy
    respond_to do |format|
      format.html { redirect_to car_infos_url, notice: 'Car info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car_info
      @car_info = CarInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_info_params
      params.require(:car_info).permit(:model, :year, :condition, :location_address, :location_city, :location_state, :location_zip, :price, :status, :sold_by)
    end
end

car-listings/app/helpers/car_infos_helper.rb
module CarInfosHelper
end

car-listings/app/views/car_infos/_form.html.erb
<%= form_for(car_info) do |f| %>
  <% if car_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car_info.errors.count, "error") %> prohibited this car_info from being saved:</h2>

      <ul>
      <% car_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="field">
    <%= f.label :condition %>
    <%= f.text_field :condition %>
  </div>

  <div class="field">
    <%= f.label :location_address %>
    <%= f.text_field :location_address %>
  </div>

  <div class="field">
    <%= f.label :location_city %>
    <%= f.text_field :location_city %>
  </div>

  <div class="field">
    <%= f.label :location_state %>
    <%= f.text_field :location_state %>
  </div>

  <div class="field">
    <%= f.label :location_zip %>
    <%= f.text_field :location_zip %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :sold_by %>
    <%= f.text_field :sold_by %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

car-listings/app/views/car_infos/edit.html.erb
<h1>Editing Car Info</h1>

<%= render 'form', car_info: @car_info %>

<%= link_to 'Show', @car_info %> |
<%= link_to 'Back', car_infos_path %>

car-listings/app/views/car_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Car Infos</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Year</th>
      <th>Condition</th>
      <th>Location address</th>
      <th>Location city</th>
      <th>Location state</th>
      <th>Location zip</th>
      <th>Price</th>
      <th>Status</th>
      <th>Sold by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @car_infos.each do |car_info| %>
      <tr>
        <td><%= car_info.model %></td>
        <td><%= car_info.year %></td>
        <td><%= car_info.condition %></td>
        <td><%= car_info.location_address %></td>
        <td><%= car_info.location_city %></td>
        <td><%= car_info.location_state %></td>
        <td><%= car_info.location_zip %></td>
        <td><%= car_info.price %></td>
        <td><%= car_info.status %></td>
        <td><%= car_info.sold_by %></td>
        <td><%= link_to 'Show', car_info %></td>
        <td><%= link_to 'Edit', edit_car_info_path(car_info) %></td>
        <td><%= link_to 'Destroy', car_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car Info', new_car_info_path %>

car-listings/app/views/car_infos/new.html.erb
<h1>New Car Info</h1>

<%= render 'form', car_info: @car_info %>

<%= link_to 'Back', car_infos_path %>

car-listings/app/views/car_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @car_info.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car_info.year %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @car_info.condition %>
</p>

<p>
  <strong>Location address:</strong>
  <%= @car_info.location_address %>
</p>

<p>
  <strong>Location city:</strong>
  <%= @car_info.location_city %>
</p>

<p>
  <strong>Location state:</strong>
  <%= @car_info.location_state %>
</p>

<p>
  <strong>Location zip:</strong>
  <%= @car_info.location_zip %>
</p>

<p>
  <strong>Price:</strong>
  <%= @car_info.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @car_info.status %>
</p>

<p>
  <strong>Sold by:</strong>
  <%= @car_info.sold_by %>
</p>

<%= link_to 'Edit', edit_car_info_path(@car_info) %> |
<%= link_to 'Back', car_infos_path %>